import type { Term } from './types';

export const TOTAL_QUESTIONS = 50;

export const TELECOM_TERMS: Term[] = [
    { "term": "5G NR (New Radio)", "definition": "The global standard for a unified, more capable 5G wireless air interface." },
    { "term": "Latency", "definition": "The time delay for a data packet to travel from a source to a destination." },
    { "term": "Bandwidth", "definition": "The maximum rate of data transfer across a given path." },
    { "term": "MIMO (Multiple-Input Multiple-Output)", "definition": "Using multiple antennas at both the transmitter and receiver to improve communication performance." },
    { "term": "Beamforming", "definition": "A signal processing technique used to direct wireless signals to a specific receiving device." },
    { "term": "OFDMA (Orthogonal Frequency Division Multiple Access)", "definition": "A multi-user version of OFDM that allows simultaneous data transmission to several users." },
    { "term": "Network Slicing", "definition": "A virtual network architecture that allows multiple virtualized networks to be created on top of a common physical infrastructure." },
    { "term": "QAM (Quadrature Amplitude Modulation)", "definition": "A modulation scheme that conveys data by changing the amplitude of two carrier waves." },
    { "term": "SNR (Signal-to-Noise Ratio)", "definition": "A measure used in science and engineering that compares the level of a desired signal to the level of background noise." },
    { "term": "Path Loss", "definition": "The reduction in power density of an electromagnetic wave as it propagates through space." },
    { "term": "Handover / Handoff", "definition": "The process of transferring an ongoing call or data session from one channel connected to the core network to another." },
    { "term": "FDD (Frequency Division Duplex)", "definition": "A duplexing method where uplink and downlink transmissions occur on different frequency bands." },
    { "term": "TDD (Time Division Duplex)", "definition": "A duplexing method where uplink and downlink transmissions occur on the same frequency band but at different time slots." },
    { "term": "Carrier Aggregation", "definition": "A technique used to increase the data rate per user by combining multiple frequency bands." },
    { "term": "Small Cells", "definition": "Low-powered radio access nodes that have a range of 10 meters to a few kilometers." },
    { "term": "VoLTE (Voice over LTE)", "definition": "A standard for high-speed wireless communication for mobile phones and data terminals, including the Internet of things." },
    { "term": "RTT (Round-Trip Time)", "definition": "The length of time it takes for a signal to be sent plus the length of time it takes for an acknowledgment of that signal to be received." },
    { "term": "Backhaul", "definition": "The portion of a network that comprises the intermediate links between the core network and the small subnetworks at the 'edge' of the entire hierarchical network." },
    { "term": "Edge Computing", "definition": "A distributed computing paradigm that brings computation and data storage closer to the sources of data." },
    { "term": "IoT (Internet of Things)", "definition": "A system of interrelated computing devices, mechanical and digital machines that are provided with unique identifiers." },
    { "term": "eMBB (Enhanced Mobile Broadband)", "definition": "A 5G use case that focuses on providing significantly faster data rates and better user experience." },
    { "term": "URLLC (Ultra-Reliable Low-Latency Communication)", "definition": "A 5G use case for mission-critical applications that require uninterrupted and robust data exchange." },
    { "term": "mMTC (Massive Machine-Type Communications)", "definition": "A 5G use case that focuses on connecting a massive number of low-power, low-cost devices." },
    { "term": "RAN (Radio Access Network)", "definition": "A type of network infrastructure used in mobile telecommunications that connects user equipment to the core network." },
    { "term": "Virtual RAN (vRAN)", "definition": "A RAN implementation where the baseband unit functions are virtualized and run on general-purpose hardware." },
    { "term": "Open RAN (O-RAN)", "definition": "A movement to disaggregate traditional RAN systems into open and interoperable components." },
    { "term": "Spectrum", "definition": "The range of electromagnetic frequencies used for wireless communication." },
    { "term": "Sub-6 GHz", "definition": "5G frequencies below 6 GHz, providing a balance of coverage and capacity." },
    { "term": "mmWave (Millimeter Wave)", "definition": "Very high-frequency bands (typically 24 GHz and above) used for 5G, offering massive capacity but limited range." },
    { "term": "Throughput", "definition": "The actual rate of successful data transfer over a communication channel." },
    { "term": "Codec (Coder-Decoder)", "definition": "A device or computer program which encodes or decodes a digital data stream or signal." },
    { "term": "Jitter", "definition": "The variation in the delay of received packets in a data stream over a network." },
    { "term": "Packet Loss", "definition": "Occurs when one or more packets of data traveling across a computer network fail to reach their destination." },
    { "term": "Duplexing", "definition": "A point-to-point system composed of two or more connected parties or devices that can communicate with one another in both directions." },
    { "term": "Multiplexing", "definition": "A method by which multiple analog or digital signals are combined into one signal over a shared medium." },
    { "term": "IMSI (International Mobile Subscriber Identity)", "definition": "A unique number, usually 15 digits, associated with all cellular network users." },
    { "term": "IMEI (International Mobile Equipment Identity)", "definition": "A unique number for identifying a device on a mobile network." },
    { "term": "SIM (Subscriber Identity Module)", "definition": "An integrated circuit that securely stores the IMSI and the related key used to identify and authenticate subscribers." },
    { "term": "eSIM (Embedded SIM)", "definition": "A digital SIM that allows you to activate a cellular plan from your carrier without having to use a physical SIM card." },
    { "term": "LTE (Long-Term Evolution)", "definition": "A standard for wireless broadband communication for mobile devices and data terminals, based on the GSM/EDGE and UMTS/HSPA technologies." },
    { "term": "Wi-Fi 6 (802.11ax)", "definition": "The next-generation standard in WiFi technology, also known as 'AX WiFi'." },
    { "term": "Bluetooth", "definition": "A short-range wireless technology standard that is used for exchanging data between fixed and mobile devices over short distances." },
    { "term": "NFC (Near Field Communication)", "definition": "A set of communication protocols for communication between two electronic devices over a distance of 4 cm or less." },
    { "term": "HetNet (Heterogeneous Network)", "definition": "A network that connects computers and other devices with different operating systems and/or protocols." },
    { "term": "RoI (Region of Interest)", "definition": "A selected subset of samples within a dataset identified for a particular purpose." },
    { "term": "CSI (Channel State Information)", "definition": "The known channel properties of a communication link." },
    { "term": "Modulation", "definition": "The process of varying one or more properties of a periodic waveform, called the carrier signal, with a modulating signal that typically contains information to be transmitted." },
    { "term": "Demodulation", "definition": "The act of extracting the original information-bearing signal from a modulated carrier wave." },
    { "term": "Frequency Reuse", "definition": "The system of assigning and reusing frequencies to improve efficiency and capacity in cellular networks." },
    { "term": "Cellular Network", "definition": "A communication network where the last link is wireless. The network is distributed over land areas called cells, each served by at least one fixed-location transceiver." }
];